In [12]:
from typing_extensions import Concatenate
#import
import numpy as np
import torch

'''view(), squeeze(), and unsqueeze() adjust their shape and dimension 
while keeping the number of elements'''

#5.View = Reshape(Numpy)
'''*** Very important ****
Resize(reshape) the tensor while keeping the number of elements'''
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

print(ft.shape) #torch.Size([2, 2, 3])

#Change from 3D tensor to 2D tensor
print(ft.view([-1, 3])) # Change ft tensor to a size of (?, 3)
#tensor([[ 0.,  1.,  2.],[ 3.,  4.,  5.],[ 6.,  7.,  8.],[ 9., 10., 11.]])
print(ft.view([-1, 3]).shape) #torch.Size([4, 3])

#Change the shape while maintaining the 3D dimension 
print(ft.view([-1, 1, 3])) #tensor([[[ 0.,  1.,  2.]], [[ 3.,  4.,  5.]], [[ 6.,  7.,  8.]],[[ 9., 10., 11.]]])
print(ft.view([-1, 1, 3]).shape) #torch.Size([4, 1, 3])

#6. Squeeze
'''Remove dimension which is 1'''
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape) #torch.Size([3, 1]

print(ft.squeeze()) #remove 2th dimension which is 1. -> tensor([0., 1., 2.])
print(ft.squeeze().shape) #torch.Size([3])

#7. Unsqueeze
'''특정 위치에 1인 차원을 추가한다'''
ft = torch.Tensor([0, 1, 2])
print(ft.shape) #(3,) torch.Size([3])
#첫번째 차원에 1인 차원을 추가
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미
#tensor([[0., 1., 2.]])
print(ft.unsqueeze(0).shape) #torch.Size([1, 3])
#(3,)의 크기를 가졌던 1차원 벡터가 (1, 3)의 2차원 텐서로 변경됨
#view로 구현시 다음과 같음: 2차원으로 바꾸고 싶으면서 첫번째 차원은 1이기를 원한다면 view에서 (1, -1)을 인자로 사용

print(ft.view(1, -1))
print(ft.view(1, -1).shape) #torch.Size([1, 3])

print(ft.unsqueeze(1)) #tensor([[0.],[1.],[2.]])
print(ft.unsqueeze(1).shape) #torch.Size([3, 1])

#인자로 -1추가
#-1은 인덱스 상으로 마지막 차원을 의미=마지막 차원에 1인 차원을 추가
print(ft.unsqueeze(-1)) #tensor([[0.],[1.],[2.]])
print(ft.unsqueeze(-1).shape) #torch.Size([3, 1])

#8. Type Casting
'''Convert data type'''
lt = torch.LongTensor([1, 2, 3, 4])
print(lt) #tensor([1, 2, 3, 4])
#type casting: convert long -> float
print(lt.float()) #tensor([1., 2., 3., 4.])

bt = torch.ByteTensor([True, False, False, True])
print(bt) #tensor([1, 0, 0, 1], dtype=torch.uint8)
#type casting: convert byte -> long/float
print(bt.long()) #tensor([1, 0, 0, 1])
print(bt.float()) #tensor([1., 0., 0., 1.])

#9. Concatenate
'''두 텐서를 연결. torch.cat([ ]). 어느 차원을 늘릴 것인지를 인자로 '''
'''딥 러닝에서는 주로 모델의 입력 또는 중간 연산에서 두 개의 텐서를 연결하는 경우가 많습니다. 
두 텐서를 연결해서 입력으로 사용하는 것은 두 가지의 정보를 모두 사용한다는 의미를 가지고 있습니다.'''
x = torch.FloatTensor([[1, 2], [3, 4]]) #|x| = (2,2)
y = torch.FloatTensor([[5, 6], [7, 8]]) #|y| = (2,2)

print(torch.cat([x, y], dim=0)) #(4,2). tensor([[1., 2.], [3., 4.],[5., 6.],[7., 8.]])
print(torch.cat([x, y], dim=1)) #(2,4). tensor([[1., 2., 5., 6.],[3., 4., 7., 8.]])

#10. Stacking
'''연결(concatenate)을 하는 또 다른 방법
연결을 하는 것보다 스택킹이 더 편리할 때가 있는데, 이는 스택킹이 많은 연산을 포함하고 있기때문'''
x = torch.FloatTensor([1, 4]) #|x|=|y|=|z|=(2,)
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(torch.stack([x, y, z])) #tensor([[1., 4.],[2., 5.],[3., 6.]]) size: (3,2)
#스택킹은 사실 많은 연산을 한 번에 축약하고 있음.위 작업은 아래의 코드와 동일
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))
#x.unsqueeze(0),y.unsqueeze(0),z.unsqueeze(0): (2,) -> (1,2)
#cat(~~~, dim = 0): (1,2) -> (3,2)

print(torch.stack([x, y, z], dim=1)) #두번째 차원이 증가하도록 쌓으라는 의미
#[[1],[4]], [[2],[5]], [[3],[6]] -> tensor([[1., 2., 3.],[4., 5., 6.]])

#11. One and Zeros
'''0으로 채워진 텐서와 1로 채워진 텐서
동일한 크기(shape)지만 0/1으로만 값이 채워진 텐서를 생성'''
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]]) #|x| = (2,3)
print(torch.ones_like(x)) #tensor([[1., 1., 1.], [1., 1., 1.]])
print(torch.zeros_like(x)) #tensor([[0., 0., 0.],[0., 0., 0.]])

#12. In-place Operation (덮어쓰기 연산)
'''_붙임. 메모리에 새로 선언하지 않고 기존 tensor에 저장'''
x = torch.FloatTensor([[1, 2], [3, 4]]) 
print(x.mul(2.)) #tensor([[2., 4.],[6., 8.]])
print(x) #tensor([[1., 2.], [3., 4.]])

#In-Place operation
print(x.mul_(2.))#tensor([[2., 4.],[6., 8.]])
print(x)#tensor([[2., 4.],[6., 8.]])

torch.Size([2, 2, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])
tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])
torch.Size([3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])
